name: Validate Package Version

on:
  pull_request:
    paths:
      - "package.json"
    types:
      - synchronize

jobs:
  validate-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check branch names
        run: |
          # Get the base and head branch names from the GitHub context
          BASE_BRANCH=$(echo $GITHUB_BASE_REF)
          HEAD_BRANCH=$(echo $GITHUB_HEAD_REF)

          # Check if the base branch is "dev" and the head branch is not "qa" or "main"
          if [ "$BASE_BRANCH" == "develop" ] && [ "$HEAD_BRANCH" != "qa" ] && [ "$HEAD_BRANCH" != "main" ]; then
            # Get the current version in the base branch
            BASE_VERSION=$(git show origin/dev:package.json | jq -r '.version')

            # Get the version in the pull request
            PR_VERSION=$(jq -r '.version' package.json)

            # Check if the versions match
            if [ "$BASE_VERSION" != "$PR_VERSION" ]; then
              echo "Error: Version in package.json was modified. Please do not modify the version manually."
              exit 1
            fi
          fi
        shell: bash
